@extends('frontend.layouts.app')
@section('title','Why Solar - ')
@section('content')

    <!-- Breadcrumb Area  -->
    <div class="breadcrumb-area dark-bg">
        <div class="breadcrumb-inner">
            <h2 class="text-white">Why Solar</h2>
            <h6 class="text-white"><a href="{{url('/')}}">Home</a> / <a class="text-white cursor-auto">About Solar</a> / Why Solar</h6>
        </div>
    </div>

 <section class="py-5 bg-gray">
        <div class="container">
            <div class="row d-flex align-items-center business-card p-lg-0 p-3 mb-lg-5 mb-4" id="inquiry">
               <div class="col-lg-6 px-0">
                <img src="{{asset('frontend/assets/img/service/save.png')}}" alt="" class="w-100">
               </div>
               <div class="col-lg-6 pt-lg-0 pt-4 px-lg-5 px-0">
                <h3 class="blog-details_title mb-md-3 mb-2 text-capitalize">Save on electricity bills</h3>
                <p>Installing solar panels significantly reduces monthly electricity bills and dependence on the power grid. This energy independence protects against rising electricity costs and volatile fuel prices. With analysts forecasting continued increases in electricity rates, solar remains a cost-effective solution and long-term investment in the future. </p>
               </div>
            </div>
            <div class="row d-flex align-items-center business-card p-lg-0 p-3 mb-lg-5 mb-4" id="inward">
                <div class="col-lg-6 px-0 order-lg-2 order-1">
                 <img src="{{asset('frontend/assets/img/service/house.webp')}}" alt="" class="w-100">
                </div>
                <div class="col-lg-6 pt-lg-0 pt-4 px-lg-5 px-0 order-lg-1 order-2">
                 <h3 class="blog-details_title mb-md-3 mb-2 text-capitalize">Increase property value</h3>
                 <p>Studies have shown properties with solar systems sell up to 20 percent faster and at a 17 percent premium compared to homes without such systems. A solar installation makes your property more attractive to buyers, increasing its resale value.</p>
                </div>
             </div>

             <div class="row d-flex align-items-center business-card p-lg-0 p-3" id="guidance">
                <div class="col-lg-6 px-0 ">
                 <img src="{{asset('frontend/assets/img/service/carbon.png')}}" alt="" class="w-100">
                </div>
                <div class="col-lg-6 pt-lg-0 pt-4 px-lg-5 px-0 order-lg-2 order-1">
                 <h3 class="blog-details_title mb-md-3 mb-2 text-capitalize">Reduce your carbon footprint</h3>
                 <p>Unlike energy generated by fossil fuels, solar doesn’t release harmful carbon dioxide (CO2) emission. Sustainable carbon-free energy solutions such as solar are crucial to slowing the pace of climate change and preventing further damage to the environment. </p>
                </div>
             </div>

        </div>
    </section>


@endsection
